# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 12:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.TextField()),
                ('resource', models.TextField()),
                ('provider', models.TextField()),
                ('title', models.TextField()),
                ('version', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.TextField()),
                ('resource', models.TextField()),
                ('shell', models.TextField()),
                ('title', models.TextField()),
                ('uid', models.IntegerField()),
                ('comment', models.TextField()),
                ('home', models.TextField()),
                ('gid', models.IntegerField()),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Volumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.TextField()),
                ('volume_name', models.TextField()),
                ('available', models.TextField()),
                ('available_bytes', models.BigIntegerField()),
                ('used', models.TextField()),
                ('capacity', models.TextField()),
                ('size', models.TextField()),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('size_bytes', models.BigIntegerField()),
                ('used_bytes', models.BigIntegerField()),
                ('device', models.TextField()),
                ('filesystem', models.TextField()),
            ],
        ),
    ]